# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('logo', models.FileField(blank=True, null=True, upload_to=organizations.models.image_upload_location)),
                ('auth_image', models.FileField(blank=True, help_text='Add Your Authorization Pdf', null=True, upload_to=organizations.models.file_upload_location)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
